### ISSUE TITLE
Please add instructions for triggering this Skill into README.md

### ISSUE THREAD

**Issue by KathyReid** [RHackrid/deviloper-silly-name-maker#1]
Firstly, thank you very much for developing this Skill. 
In the README.md file, there is no information on how to trigger the Skill. 
What phrase or `Intent` does the user speak in order to trigger the Skill? 

Kind regards, 
Kathy

**Comment by KathyReid** [comment]
Thank you so much for the update! Appreciated!

**Comment by RHackrid** [comment]
No problem. Thanks for the issue and excuse the delay. I didn't know that i have to watch my own repo via github to get notified in case of new issues.
